id = "zedokai"
name = "Zedokai"
version = "1.2.2"
schema_version = 1
authors = ["slymax <contact@slymax.com>"]
repository = "https://github.com/slymax/zedokai"
description = "a theme for Zed based on the Monokai Pro color scheme"
